### ISSUE TITLE
SW porting

### ISSUE THREAD

**Issue by pattacini** [robotology/periPersonalSpace#6]
Port SW to robotology

**Comment by pattacini** [comment]
@alecive I'd say the project is mature enough to be ported in robotology.
Can I do this this morning?

**Comment by alecive** [comment]
I'd say that it is ready to be moved, but I was thinking that a part of it, i.e. the library related to the Taxel and iCubSkin class, would be probably better suited for the skindynlib. They are a set of classes and methods that would be beneficial for many users of the iCub's skin. What do you think?

**Comment by pattacini** [comment]
I agree. Then, let's do like the following:
- extend `skindynlib` with the new functionality
- remove that functionality from `periPersonalSpace` and test
- move `periPersonalSpace` in robotology

**Comment by alecive** [comment]
Ok. For that then we should wait at least the reharsal :)

**Comment by pattacini** [comment]
no problem, open a new issue to keep track of this request.

**Comment by alecive** [comment]
Done.
